import React from "react";
import {
  FiCalendar, FiBookmark, FiTrendingUp, FiBarChart2,
  FiTarget, FiInfo, FiCpu,
} from "react-icons/fi";

export default function ReportDisplay({ report, reportRef }) {
  if (!report) return null;

  return (
    <div ref={reportRef} className="bg-white border border-slate-200 rounded-2xl shadow-sm overflow-hidden animate-fade-in">
      {/* Header banner */}
      <div className="bg-gradient-to-br from-slate-900 via-blue-950 to-indigo-900 px-8 py-10 text-white">
        <div className="flex flex-wrap items-center gap-3 text-blue-300 text-xs mb-4">
          <span className="flex items-center gap-1.5">
            <FiCalendar className="w-3.5 h-3.5" /> {report.date}
          </span>
          <span className="w-1 h-1 rounded-full bg-blue-400" />
          <span className="flex items-center gap-1.5">
            <FiCpu className="w-3.5 h-3.5" /> CrewAI · LangGraph · LLaMA 3.3
          </span>
        </div>
        <h1 className="text-2xl md:text-3xl font-bold leading-tight">{report.title}</h1>
        <p className="text-blue-300 text-sm mt-2">Multi-agent AI Research Report</p>
      </div>

      <div className="px-6 md:px-8 py-8 space-y-10">
        {/* Executive Summary */}
        <section className="section-in">
          <Heading icon={<FiBookmark />} title="Executive Summary" />
          <p className="text-slate-700 leading-relaxed text-[15px] bg-slate-50 border border-slate-200 rounded-xl p-5">
            {report.executiveSummary}
          </p>
        </section>

        {/* Key Findings */}
        <section className="section-in">
          <Heading icon={<FiTrendingUp />} title="Key Findings" />
          <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
            {report.keyFindings?.map((f, i) => (
              <div key={i} className="flex gap-3 bg-blue-50 border border-blue-100 rounded-xl p-4">
                <div className="w-7 h-7 rounded-lg bg-blue-600 text-white text-xs font-bold flex-shrink-0 flex items-center justify-center mt-0.5">
                  {i + 1}
                </div>
                <p className="text-slate-700 text-sm leading-relaxed">{f}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Detailed Analysis */}
        <section className="section-in">
          <Heading icon={<FiBarChart2 />} title="Detailed Analysis" />
          <div className="space-y-5">
            {report.detailedAnalysis?.map((s, i) => (
              <div key={i} className="border-l-4 border-indigo-200 pl-5">
                <h3 className="font-semibold text-slate-800 mb-2">{s.title}</h3>
                <div className="text-slate-600 text-sm leading-relaxed space-y-2">
                  {(s.content || "").split(/\n+/).filter(Boolean).map((p, j) => (
                    <p key={j}>{p}</p>
                  ))}
                </div>
              </div>
            ))}
          </div>
        </section>

        {/* Statistics */}
        <section className="section-in">
          <Heading icon={<FiBarChart2 />} title="Key Statistics" />
          <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">
            {report.statistics?.map((stat, i) => (
              <div key={i} className="bg-slate-50 border border-slate-200 rounded-xl p-4">
                <div className="text-2xl font-extrabold text-blue-600 mb-1 font-mono">
                  {extractLeadNumber(stat)}
                </div>
                <p className="text-slate-500 text-xs leading-snug">{stat}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Recommendations */}
        <section className="section-in">
          <Heading icon={<FiTarget />} title="Recommendations" />
          <div className="space-y-3">
            {report.recommendations?.map((r, i) => (
              <div key={i} className="flex items-start gap-3 bg-emerald-50 border border-emerald-100 rounded-xl p-4">
                <div className="w-6 h-6 rounded-lg bg-emerald-600 text-white text-xs font-bold flex-shrink-0 flex items-center justify-center mt-0.5">
                  {i + 1}
                </div>
                <p className="text-slate-700 text-sm leading-relaxed">{r}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Conclusion */}
        <section className="section-in">
          <Heading icon={<FiInfo />} title="Conclusion" />
          <p className="text-slate-700 text-[15px] leading-relaxed">{report.conclusion}</p>
        </section>

        {/* Sources note */}
        <div className="border-t border-slate-100 pt-5">
          <p className="text-xs text-slate-400 italic">{report.sourcesNote}</p>
          <p className="text-xs text-slate-300 mt-1">
            Generated by CrewAI multi-agent system (Planner → Researcher → Analyst → Writer) orchestrated by LangGraph
          </p>
        </div>
      </div>
    </div>
  );
}

function Heading({ icon, title }) {
  return (
    <div className="flex items-center gap-2 mb-4">
      <span className="text-blue-500">{icon}</span>
      <h2 className="font-bold text-slate-800 text-[17px]">{title}</h2>
      <div className="flex-1 h-px bg-slate-200 ml-1" />
    </div>
  );
}

function extractLeadNumber(stat) {
  const m = stat.match(/[\d,.]+%?/);
  return m ? m[0] : "—";
}
